- name: "ufw allow fabric"
  remote_user: root
  ufw:
    interface: eth0
    direction: in
    rule: allow
    proto: tcp
    port: 7050:7054

- name: "copy peer artifacts"
  synchronize:
    src: "/home/{{ fabric.user }}/build/fabric/org{{ org_id }}/pkg-peer{{ peer_id }}org{{ org_id }}"
    dest: "/home/{{ fabric.user }}"
  delegate_to: "{{ groups['build'][0] }}"

- name: "add peer systemd service file"
  remote_user: root
  template:
    src: "../files/peer.service"
    dest: "/etc/systemd/system/peer.service"
    mode: 0644
